### ISSUE TITLE
Add Perl 6 syntax highlighting on exercism.io

### ISSUE THREAD

**Issue by mienaikage** [exercism/perl6#164]
Currently, there is no highlighting for Perl 6 code on exercism.io. It appears that exercism.io is using [Rouge](https://github.com/jneen/rouge):
https://github.com/exercism/exercism.io/blob/master/lib/exercism/syntax_highlighter.rb

Perhaps it would be possible to port from [pygments](https://bitbucket.org/hoelzro/pygments-main/src/92f4deeaa28215ee58779aa496e44af7f1ab1343/pygments/lexers/perl.py?at=default&fileviewer=file-view-default) to Rouge?

**Comment by mienaikage** [comment]
There's an existing issue to add support for Perl 6 in https://github.com/jneen/rouge/issues/390

**Comment by kotp** [comment]
Is highlighting at the exercism/exercism.io repository level?

**Comment by kytrinyx** [comment]
If the track ID doesn't match the language name in jneen/rouge, then we need to add it to the map of ids to rouge names: https://github.com/exercism/exercism.io/blob/master/lib/exercism/syntax_highlighter.rb#L6-L16

**Comment by habere-et-dispertire** [comment]
Raku syntax highlighting appears sometimes off.

Strangely not in the web editor but in published solutions.

For an example, look at lines 4-5 of [this Luhn solution](https://exercism.org/tracks/raku/exercises/luhn/solutions/habere-et-dispertire). It appears the regex containing `<digit>` throws things out of kilter.

**Comment by kotp** [comment]
@habere-et-dispertire can you open a new issue?  This one is for "no highlighting" as opposed to broken highlighting.

**Comment by kotp** [comment]
There is a related issue upstream https://github.com/rouge-ruby/rouge/issues/390

**Comment by habere-et-dispertire** [comment]
New Issue [#520 ](https://github.com/exercism/raku/issues/520).

**Comment by kotp** [comment]
Nice, thanks for the breadcrumbs.
