### ISSUE TITLE
Update ABOUT.md so that it complies with meta#85

### ISSUE THREAD

**Issue by kotp** [exercism/perl6#251]
Re: exercism/meta#85

In summary, ABOUT.md should now only use:

- Bold
- Italics
- Links
- Bullet lists
- Number lists
- Each sentence should be on its own line
- Paragraphs separated by an empty line
- Explicit <br/> used to split a paragraph into lines without spacing between them (discouraged).

**Comment by mienaikage** [comment]
PR in https://github.com/exercism/perl6/pull/252

**Comment by kotp** [comment]
Thank you @mienaikage
